# Generated by Django 3.2.4 on 2021-06-20 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('VIÑ', 'Viña del Mar'), ('SER', 'La Serena'), ('PUC', 'Pucon'), ('VIL', 'Villarrica'), ('VAL', 'Valdivia'), ('IQU', 'Iquique'), ('FRU', 'Frutillar')], default='Iquique', max_length=3)),
                ('precio', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('camas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('chek_out', models.DateTimeField()),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arriendo.depto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
