# Generated by Django 3.2.4 on 2021-06-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arriendo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='chek_out',
            new_name='check_out',
        ),
    ]
