# Generated by Django 3.2.4 on 2021-06-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendo', '0005_alter_depto_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depto',
            name='category',
            field=models.CharField(choices=[('VIN', 'Vina del Mar'), ('SER', 'La Serena'), ('PUC', 'Pucon'), ('VIL', 'Villarrica'), ('VAL', 'Valdivia'), ('IQU', 'Iquique'), ('FRU', 'Frutillar')], default='Iquique', max_length=3),
        ),
    ]
